user daemon
pidfile /var/tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

resolver {
    # 使用和 Dnsmasq 一样的上游DNS，保持一致性
    nameserver 8.8.8.8
    nameserver 1.1.1.1
    nameserver 2001:4860:4860::8888
    nameserver 2606:4700:4700::1111

    # 修改解析模式，优先使用IPv4，但支持IPv6作为备用
    # 可选值: ipv4_only, ipv6_only, ipv4_first, ipv6_first
    mode ipv4_first
}
listener 0.0.0.0:80 {
    proto http
    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}
listener 0.0.0.0:443 {
    proto tls
    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table {

}
